-- Colors
CLR_BLACK = 0
CLR_DARK_BLUE = 1
CLR_DARK_PURPLE = 2
CLR_DARK_GREEN = 3
CLR_BROWN = 4
CLR_DARK_GREY = 5
CLR_LIGHT_GREY = 6
CLR_WHITE = 7
CLR_RED = 8
CLR_ORANGE = 9
CLR_YELLOW = 10
CLR_GREEN = 11
CLR_BLUE = 12
CLR_LAVENDER = 13
CLR_PINK = 14
CLR_LIGHT_PEACH = 15

-- Buttons
BUTTON_LEFT = 0
BUTTON_RIGHT = 1
BUTTON_UP = 2
BUTTON_DOWN = 3
BUTTON_O = 4
BUTTON_X = 5

-- General
DIRECTION_LEFT = -1
DIRECTION_NONE = 0
DIRECTION_RIGHT = 1
