name: Release
on:
  push:
    branches:
      - main

jobs:
  SemanticRelease:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
