name: Release
on:
  push:
    branches:
      - main

jobs:
  SemanticRelease:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Deploy:
    name: Deploy To Itch.io
    runs-on: ubuntu-latest
    needs:
      - UploadArtifacts
      - SemanticRelease
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - linux
          - osx
    steps:
      - name: Download Artifacts
        if: needs.SemanticRelease.steps.semantic.outputs.new_release_published == 'true'
        uses: actions/download-artifact@v3
        with:
          name: ${{ secrets.ARTIFACT_NAME }}
      - name: Upload ${{ matrix.channel }} Binary To Itch.io
        if: needs.SemanticRelease.steps.semantic.outputs.new_release_published == 'true'
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.channel }}
          ITCH_USER: ${{ secrets.ITCH_IO_USERNAME }}
          ITCH_GAME: ${{ secrets.ITCH_IO_PROJECT_NAME }}
          PACKAGE: ${{ secrets.ARTIFACT_NAME }}_${{ matrix.channel }}.zip
          VERSION: ${{ needs.SemanticRelease.steps.semantic.outputs.new_release_version }}
